language: bash
sudo: required
python:
- '3.5'
env:
  global:
  - PATH="${HOME}/bin:${PATH}"
  - TMPDIR="${TMPDIR:-/tmp}"
install:
- mkdir -p "${HOME}/bin"
- if ! terraform version ; then
    pushd "${TMPDIR}" ;
    curl -sSL
      -o terraform.zip
      "https://releases.hashicorp.com/terraform/0.8.2/terraform_0.8.2_linux_amd64.zip" ;
    unzip terraform.zip ;
    mv -v terraform "${HOME}/bin/terraform" ;
    chmod +x "${HOME}/bin/terraform" ;
    popd ;
    terraform version ;
  fi
before_script:
- chmod +x .travis/*
- ".travis/setup.sh"
- pushd two-tier-vpc
- terraform get
- terraform plan
script:
- ".travis/test.sh"
after_script:
- ".travis/teardown.sh"
- terraform destroy -f
env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
  - secure: "CHAMtaHD8do5hkrsP4R506MJW6DAXZtEU8WqiswY7rRGqOQau5BhOSWlb2HhCfaTl+a183MpipwIDUz1yyOJml6pF2T7ck3lNJQHBPVxqyVpzdY2GknB6bwjc62eodWPAIHVfYfZGDlVv0b70dqt85KUqgM012IyQHm2mz27TVydwdwsQ9ZqZZXrICySl5LNgrnG2Q7HaHhpzNEBLvfzLLzFn4IESo1+hBX13EAcXxq8NF94LhacvUijup3goPoO9MPhJybmUaLExkTq4cfTtle8ZNsNa4+tXj7WbaKccr2VgKGTsVjaCkCysvyU1O8reQ0IK8fHFaZ08IlYeovftPkYhUxTq8amvnXcdHG7jbSt48dR47GyxhbmZ+61XXfbtCr9fDx/RSv6bVus7+5rlu2iwCE1YqfDKYQN1kGjkiNr76miITrPJl+yWXmAVbTuMV3hY6rNhFmtjWzqYU/FWB9v+Ufzhp+SUK+YaAawreNt2NvL7Z71B7Jm/Q2+BQwfk8vpfV3GACmjh87txk+gegHRktsOT5bnyYQpC0rW8y5S7KfOxTINVkapwxktygoIdO5YAnqsONVwogmoLK9TWLJiC8JpO+WP3xxjzOvRsOP8dGiJGyn9yuB3daqPyEn9ryk1bE/wDGanauYDReHw8GZe68MAM9snlSBQs3FPfUs="
  - secure: "IH600IVvf/18E1RTEIXRUvA53wcx4ol/D6JM3MAiSc43WZvHznD8hqTZ8wK8/svo/9aYHxkmhbRsw5GfV+VdHcxnWU6QM0DvVFw8kgzuzEJtUYtB4VlnVceTETFb16T64puu507FRqjhRHWdqpMGwj6YB38t2/ZDtV9od1D/x3LzKXieqC1XjSc3fFcDGl9ul2WLxu9KVh/uoDXt3JaI4Kdgaa/Mv1Oul9ygi0brpkDTI0XEL47L2iGatMYNVl68en0eALiADrRbEgG5hdM/73imxqtqANWbWgRXUbLklEssNqtZ2e+Pss+DHKqAoj3wb8/XgavdhlGgeGqQcJUVSgKvDoB5noGF4jr6bMyy2dKXQXpC8qGoFeQtNg3Sv5o6BUrTraf+SgtFO3+xhA0qkLIwL8XdUHDv/UHp+LMjmYyhQ5ZMbYByVediAgq6vs35SK3Pns9jt/sLzG2IwmS+5RNO1HvD02Du4SxAO8JYHadXdFiZkY14UHITPySvSA8Pa7aYYZ3ivzRPyG6NQMCN3e+D6XZeGofZBb0XUNSDS6MOCWLYxrsUb+US/wzoEOWPkfKE0rMHtcP55/w/kjExT8gUhiCAGU7I7yGAE7Bc+OWk1Uj8th+ugO//ckaugGyBCXhCpg0b05WfKefMvoGC+VmNUICVihsKbHKdVLzrSy4="
